### ISSUE TITLE
bug report! conflict with register

### ISSUE THREAD

**Issue by justemu** [cosmocode/dokuwiki-plugin-submgr#1]
If I create rules in Automatic Subscription Management, the register function of the site fails. That is ...
I get a HTTP ERROR 500, if I fill the register form and submit.

The register function restored if I deleted all the rules in Automatic Subscription Management.

--
Error in the log:

PHP Fatal error:  Uncaught TypeError: Argument 3 passed to auth_isMember() must be of the type array, null given, called in /data/wwwroot/mba.touyan.net/lib/plugins/submgr/helper.php on line 97 and defined in /data/wwwroot/mba.touyan.net/inc/auth.php:575\nStack trace:\n#0 /data/wwwroot/mba.touyan.net/lib/plugins/submgr/helper.php(97): auth_isMember('user', 'test', NULL)\n#1 /data/wwwroot/mba.touyan.net/lib/plugins/submgr/action.php(41): helper_plugin_submgr->runRules('test', NULL)\n#2 /data/wwwroot/mba.touyan.net/inc/events.php(211): action_plugin_submgr->handle_auth_user_change(Object(Doku_Event), NULL)\n#3 /data/wwwroot/mba.touyan.net/inc/events.php(70): Doku_Event_Handler->process_event(Object(Doku_Event), 'BEFORE')\n#4 /data/wwwroot/mba.touyan.net/lib/plugins/auth.php(134): Doku_Event->advise_before(true)\n#5 /data/wwwroot/mba.touyan.net/inc/auth.php(949): DokuWiki_Auth_Plugin->triggerUserMod('create', Array)\n#6 /data/wwwroot/mba.touyan.net/inc/actions.php(90): register()\n#7 /data/wwwroot/mba.touyan.net/doku.php(124): act_dispatc in /data/wwwroot/mba.touyan.net/inc/auth.php on line 575, referer: http://mba.touyan.net/start?do=register

**Comment by justemu** [comment]
I fix the bug by adding the codes in action.php(line 40) to determine wether data['params'][4] is null. Change it to an empty array if its value is null.

`$group = $event->data['params'][4];
if (is_null($group)){
$group=array();
}`

And the problem solved.
